server: 8080

spring:
  profiles:
    default: dev

jwt:
  secret: aaGVsbG8tbXktcmVhbC1uYW1lLWlzLWppbndvbi10aGlzLWtleS1pcy12ZXJ5LWltcG9ydGFudC1zby1iZS1jYXJlZnVsLXRoYW5rLXlvdQ==
  access-token-expire-time: 1800000
  refresh-token-expire-time: 604800000


logging:
  level:
    com.dev: debug
    org.hibernate.sql: debug
    org.hibernate.type: trace

#spring:
#
#  h2:
#    console:
#      enabled: true
#
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/cpt
#    username: sa
#    password: zoqtmxhs
#    driver-class-name: org.h2.Driver
#
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: none
#    properties:
#      hibernate:
#        format_sql: true
#        show_sql: true
#
#  jackson:
#    serialization:
#      fail-on-empty-beans: false
#
#
#jwt:
#  secret: aaGVsbG8tbXktcmVhbC1uYW1lLWlzLWppbndvbi10aGlzLWtleS1pcy12ZXJ5LWltcG9ydGFudC1zby1iZS1jYXJlZnVsLXRoYW5rLXlvdQ==
#  access-token-expire-time: 1800000
#  refresh-token-expire-time: 604800000
#
#
#
#logging.level:
#  org.hibernate.sql: debug
#  org.hibernate.type: trace
#  com.dev : debug