server:
  port: 8080

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql:aurora://database-2-instance-1.cjnvttft5wgb.ap-northeast-2.rds.amazonaws.com:3306/capstone?serverTimeZone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: Duddidrod123!
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  jackson:
    serialization:
      fail-on-empty-beans: false


